/**
 * Generates api/_lib/catalog.json — run: npm run catalog:build
 * Keeps seed self-contained for Vercel (no src/ imports at runtime).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { deyeProducts } from "../src/app/data/deyeProducts.js";
import { nssProductsSeed } from "../src/app/data/nssProductsSeed.js";
import { ukMessages } from "../src/app/i18n/messages.uk.js";
import { enMessages } from "../src/app/i18n/messages.en.js";

type SeedProduct = {
  id: string;
  category: string;
  name: string;
  badge: string;
  color: string;
  specs: { label: string; value: string }[];
  tags: string[];
  warranty: string;
  highlightUk: string;
  highlightEn: string;
  descriptionUk: string;
  descriptionEn: string;
  image?: string;
  featured?: boolean;
};

function lookup(obj: Record<string, unknown>, path: string): string {
  const parts = path.split(".");
  let cur: unknown = obj;
  for (const p of parts) {
    if (cur === null || cur === undefined || typeof cur !== "object") return "";
    cur = (cur as Record<string, unknown>)[p];
  }
  return typeof cur === "string" ? cur : "";
}

function tUk(key: string): string {
  const path = key.startsWith("productsPage.") ? key : `productsPage.${key}`;
  return lookup(ukMessages as unknown as Record<string, unknown>, path);
}

function tEn(key: string): string {
  const path = key.startsWith("productsPage.") ? key : `productsPage.${key}`;
  return lookup(enMessages as unknown as Record<string, unknown>, path);
}

function descUk(highlightKey?: string): string {
  if (!highlightKey) return "";
  return lookup(ukMessages as unknown as Record<string, unknown>, `productsPage.desc.${highlightKey}`);
}

function descEn(highlightKey?: string): string {
  if (!highlightKey) return "";
  return lookup(enMessages as unknown as Record<string, unknown>, `productsPage.desc.${highlightKey}`);
}

function warrantyUk(raw: string, id: string): string {
  if (id.startsWith("deye-")) return tUk("productsPage.wStd");
  return raw
    .replace("5jr standaard", tUk("productsPage.wStd"))
    .replace("10jr prestatie", tUk("productsPage.w10y"))
    .replace("15jr materiaal / 30jr vermogen", tUk("productsPage.wMat"))
    .replace("8000+ cycli", tUk("productsPage.wCycles"))
    .replace("TÜV Gecertificeerd", tUk("productsPage.wTuv"))
    .replace("BNEF Tier 1", tUk("productsPage.wBnef"));
}

const catalog: SeedProduct[] = nssProductsSeed.map((p) => ({
  id: p.id,
  category: p.category,
  name: p.name,
  badge: p.badge,
  color: p.color,
  specs: p.specs,
  tags: p.tags || [],
  warranty: p.warranty,
  highlightUk: p.highlightUk || "",
  highlightEn: p.highlightEn || "",
  descriptionUk: p.descriptionUk || descUk(p.highlightKey) || "",
  descriptionEn: p.descriptionEn || descEn(p.highlightKey) || "",
  image: p.image,
  featured: p.featured,
}));

for (const p of deyeProducts) {
  catalog.push({
    id: p.id,
    category: p.category,
    name: p.name,
    badge: p.badge,
    color: p.color,
    specs: p.specs,
    tags: (p.tagKeys || []).map((k) => tUk(k)).filter(Boolean),
    warranty: warrantyUk(p.warranty, p.id),
    highlightUk: p.highlightKey ? tUk(p.highlightKey) : "",
    highlightEn: p.highlightKey ? tEn(p.highlightKey) : "",
    descriptionUk: descUk(p.highlightKey),
    descriptionEn: descEn(p.highlightKey),
    image: p.image,
    featured: p.featured,
  });
}

const out = resolve("api/_lib/catalog.json");
const tsOut = resolve("api/_lib/catalogData.ts");
writeFileSync(out, JSON.stringify(catalog, null, 2));
writeFileSync(
  tsOut,
  `// Auto-generated by npm run catalog:build — do not edit\nexport const catalog = ${JSON.stringify(catalog)} as const;\n`,
);
console.log(`Wrote ${catalog.length} products to ${out} and catalogData.ts`);
